apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
      version: canary
  template:
    metadata:
      labels:
        app: vote
        version: canary
    spec:
      containers:
      - image: bhargavqwertyuiop/vote-app:102
        name: vote
        ports:
        - containerPort: 80
          name: vote
