apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
      version: stable
  template:
    metadata:
      labels:
        app: vote
        version: stable
    spec:
      containers:
      - image: bhargavqwertyuiop/vote-app:103
        name: vote
        ports:
        - containerPort: 80
          name: vote
